HW7: Катерина Дедученко и Арсений Терехов
katusha97/Roguelike pull request #2
Opened 2021-05-03 00:48 UTC by simpletonDL

Работа в процессе, мы решили сделать упор на мультиплеер, чтобы боты были как полноценные игроки.

2021-05-14 20:23 UTC, ottergottaott requested changes
Еще нужны комментарии и тесты

Также напомню, что в задании требовалось

> 
> Несколько видов противников
> 
>     Должны различаться видом
>     Должны различаться поведением
>         Могут быть агрессивными, пассивными (ходят по заранее заданному маршруту или стоят) и трусливым (бегут от игрока)
>         Используйте паттерн стратегия
>     Должен поддерживаться конус или окружность видимости у противников (дальше N метров не видят, за угол не видят и т.д.)


Пока 5

2021-05-14 20:23 UTC, ottergottaott commented on src/main/kotlin/utils/Debug.kt
> +//                player.x == x && player.y == y -> builder.append("\uD83D\uDCA9")
Не должно быть закомментированного кода

Название у файла такое себе

2021-05-14 20:23 UTC, ottergottaott commented on src/main/kotlin/server/Server.kt
> +                    val accept = serverSocket.accept()
Повторю:

> Не вижу, чтобы этот сокет где-то закрывался, когда работа с клиентом закончена

2021-05-14 20:23 UTC, ottergottaott commented on src/main/kotlin/server/Server.kt
> +                    val accept = serverSocket.accept()
И вот это заодно

> Заодно расскажите (и поймите?) почему сокеты нужно закрывать

2021-05-14 20:23 UTC, ottergottaott commented on src/main/kotlin/client/view/Drawer.kt
> +            val startY = sizeRect * world.map.sizeY + 50
Такие места стоит подробно кмментировать, в них сложно разбираться

2021-05-14 20:23 UTC, ottergottaott commented on src/main/kotlin/client/BotListener.kt
> +        var world = protocol.readUpdateWorld()
Лишнее чтение

2021-05-14 20:23 UTC, ottergottaott commented on src/main/kotlin/client/BotListener.kt
> +                is UpdateWorld -> {
Может, все-таки if использовать?

2021-05-14 20:23 UTC, ottergottaott commented on src/main/kotlin/server/engine/BotController.kt
> +                        // TODO: 1) Make stones hash table (x, y) -> Cell
Ага, или хотя бы массив-маску

2021-05-14 20:23 UTC, ottergottaott commented on src/main/kotlin/client/Bot.kt
> +    val listener = BotListener(socket)
Я не совсем понимаю почему логика бота дублируется на сервере и здесь. Оно же тоже самое делает, нет?

2021-05-14 20:23 UTC, ottergottaott commented on src/main/kotlin/common/protocol/ServerProtocol.kt
> +    fun sendServerCommand(cmd: ServerCommand) {
Несколько неиспользуемых методов

2021-05-14 20:23 UTC, ottergottaott commented on src/main/kotlin/common/protocol/ClientProtocol.kt
> +                "Socket readLine returns null (perhaps client disconnected or server close connection)"
Ага, от `ProtocolBase` не наследуемся больше, а сообщение все такое же пространное. 

Ну и тут же копирование, все еще не понимаю почему агрегирование вам не нравится

2021-05-14 20:23 UTC, ottergottaott commented on src/main/kotlin/server/engine/GameUtils.kt
> +        Cell(x+1, y),
Что-то форматирование наелось

2021-05-14 20:23 UTC, ottergottaott commented on src/main/kotlin/common/model/Id.kt
> +class Id(val id: Int) {
Эти штуки все еще можно убрать в один файл, так проще читать

2021-05-24 12:30 UTC, simpletonDL commented on src/main/kotlin/utils/Debug.kt
> +//                player.x == x && player.y == y -> builder.append("\uD83D\uDCA9")
Убрали закоментированный код. Файл переназвали в Utils

2021-05-24 12:31 UTC, simpletonDL commented on src/main/kotlin/server/Server.kt
> +                    val accept = serverSocket.accept()
С сокетами пока не очень получилось --- если мы закрываем accept после работы ServerListener, то почему-то потом всё ломается. Я пока так и не понял, почему так происходит. На счёт того, почему сокеты нужно закрывать --- наверное, если их не закрывать, то будут открыты всякие десрипторы в ОС. Так же порт  будет занят и придётся самому ручками его закрывать потом.

2021-05-24 12:31 UTC, simpletonDL commented on src/main/kotlin/client/view/Drawer.kt
> +            val startY = sizeRect * world.map.sizeY + 50
Ну тут всё-таки просто отрисовка игроков на поле происходит, как конкретно считаются координаты и кто какого цвета получается не очень важно.

2021-05-24 12:31 UTC, simpletonDL commented on src/main/kotlin/client/BotListener.kt
> +        var world = protocol.readUpdateWorld()
Убрали

2021-05-24 12:31 UTC, simpletonDL commented on src/main/kotlin/client/BotListener.kt
> +                is UpdateWorld -> {
Этот код старый, мы его решили удалилить (смотреть вопрос про ботов)

2021-05-24 12:31 UTC, simpletonDL commented on src/main/kotlin/client/Bot.kt
> +    val listener = BotListener(socket)
Да, это старый код, который мы удалили после фикса. Просто раньше боты были настоящими клиентами, который общаются с сервером через сокеты. Сейчас боты это корутины на сервере.

2021-05-24 12:31 UTC, simpletonDL commented on src/main/kotlin/common/protocol/ServerProtocol.kt
> +    fun sendServerCommand(cmd: ServerCommand) {
Да, но они просто могут потом понадобится. Идейно это команды, которые могут быть использованы при общении сервера и клиента. Поэтому не хочется их сейчас удалять

2021-05-24 12:31 UTC, simpletonDL commented on src/main/kotlin/common/protocol/ClientProtocol.kt
> +                "Socket readLine returns null (perhaps client disconnected or server close connection)"
Не очень понял, про какое копирование идёт речь? А сообщение об ошибке странное, да но я не знаю, ка клучше сделать

2021-05-24 12:31 UTC, simpletonDL commented on src/main/kotlin/server/engine/GameUtils.kt
> +        Cell(x+1, y),
Запустил автоформатирование в идее, почти ничего не поменялось)

2021-05-24 12:31 UTC, simpletonDL commented on src/main/kotlin/common/model/Id.kt
> +class Id(val id: Int) {
Да, перенесли их в World

2021-05-24 12:34 UTC, simpletonDL commented
Самое главное, что мы поправили --- сделали вот это

> Должны различаться видом
> Должны различаться поведением
>     Могут быть агрессивными, пассивными (ходят по заранее заданному маршруту или стоят) и трусливым (бегут от игрока)
>     Используйте паттерн стратегия
> Должен поддерживаться конус или окружность видимости у противников (дальше N метров не видят, за угол не видят и т.д.)

Агрессивные боты теперь бегут на игрока, пассивные бегут от игрока. При столкновении у игрока уменьшается здоровье.

2021-05-25 23:39 UTC, ottergottaott commented on src/main/kotlin/client/view/Drawer.kt
> +            val startY = sizeRect * world.map.sizeY + 50
Не очень важно до тех пор, пока это кому-то (кто, очевидно, не автор) не придется этот кусок поменять, а кому-то (ну, в реальной жизни) обязательно придется

2021-05-25 23:42 UTC, ottergottaott commented on src/main/kotlin/server/engine/GameUtils.kt
> +        Cell(x+1, y),
Пробелы вокруг операторов все еще важны, у проверяющих течет кровь из глаз, когда их нет(( 

Могу предположить, что студенту нравится, когда преподаватель страдает, но все же лучше и в мелочах придерживаться адекватных правил

2021-05-25 23:48 UTC, ottergottaott commented on src/main/kotlin/common/protocol/ClientProtocol.kt
> +                "Socket readLine returns null (perhaps client disconnected or server close connection)"
*дублирование

Видимо, с тем, что в `Common.kt`

2021-05-25 23:54 UTC, ottergottaott approved these changes
Вообще стало лучше. За кривую стратегию и отсутствие подробных комментариев ставлю 8 + за второе задание тоже 8, т.к. чего-то нифига вовремя не исправили

2021-05-25 23:54 UTC, ottergottaott commented on src/main/kotlin/server/engine/BotController.kt
> +                is ActiveAngryBot ->
Это не похоже на паттерг стратегия, это похоже на обычный `when` <s>(а чего вы ожидали услышать?)</s>.

Паттерн для того и нужен, чтобы контекст (штука, которая будет использовать стратегию, не важно как называть) не лезла во внутреннее представление и не знала ничего про класс, реализующий стратегию, а просто звала из нее нужные методы (которые описаны в интерфейсе стратегии). Тогда в контексте можно просто держать ссылку на стратегию и спокойно менять ее на другую в рантайме, если потребуется. Например, когда мы захотим добавить бафы, которые игрок может накидывать на мобов, чтобы они начинали убегать вместо агрессии.

Вообще почитайте повнимательнее, хотя бы на той же вики

2021-06-07 08:47 UTC, merged